# Generated by Django 4.1.4 on 2022-12-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_todo_completed_todo_created_todo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(max_length=1000, verbose_name='Task :'),
        ),
    ]
